### ISSUE TITLE
when add mcp, sriov-network-config-daemon does not work in k8s env.

### ISSUE THREAD

**Issue by arikachen** [k8snetworkplumbingwg/sriov-network-operator#111]
does anyone has docs to install mcp in k8s or helm command?

**Comment by zshi-redhat** [comment]
> does anyone has docs to install mcp in k8s or helm command?

Which feature are you testing?
MCP(Machine Config Pool) is openshift specific, it won't work on vanilla k8s.

**Comment by arikachen** [comment]
> > does anyone has docs to install mcp in k8s or helm command?
> 
> Which feature are you testing?

set CLUSTER_TYPE in sriov-network-config-daemon
> MCP(Machine Config Pool) is openshift specific, it won't work on vanilla k8s.

ok, i will build image locally.

**Comment by martinkennelly** [comment]
@arikachen Did building solve it for you? It didn't for me. [This code](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/f17625b70e3e00b93a795d99f9746fb7ba96ac76/pkg/daemon/daemon.go#L532) seems to be mandating MCP even for vanilla k8 deployments.

**Comment by zshi-redhat** [comment]
> @arikachen Did building solve it for you? It didn't for me. [This code](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/f17625b70e3e00b93a795d99f9746fb7ba96ac76/pkg/daemon/daemon.go#L532) seems to be mandating MCP even for vanilla k8 deployments.
> @zshi-redhat @pliurh I am not familiar with MCP but it looks like the line I specified above needs a condition to check if OpenShift or vanilla k8 before calling getNodeMachinePool().

Yes, there needs to be a conditional check on CLUSTER_TYPE.
