### ISSUE TITLE
Operator doesn't install via Helm.

### ISSUE THREAD

**Issue by mrafalx** [k8snetworkplumbingwg/sriov-network-operator#153]
Installing Operator via Helm from commit: "9bf123f64a486ef828ed41a0879a8f228f59bcb5". I'm getting below error:
`Error: unable to build kubernetes objects from release manifest: error validating "": error validating data: ValidationError(Deployment.spec): unknown field "updateStrategy" in io.k8s.api.apps.v1.DeploymentSpec
`.
I'm using kubernetes version 1.20 and Helm version 3.1.2.
Removing `updateStrategy` field from `operator.yaml` template is fixing this issue.

**Comment by e0ne** [comment]
PR #151 fixed this issue
