### ISSUE TITLE
Insufficient example for OVS HW offloading

### ISSUE THREAD

**Issue by ipatrykx** [k8snetworkplumbingwg/sriov-network-operator#169]
Hi, so currently I'm tying to to set the OVS HW offloading up using [this instruction](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/ovs-hw-offload.md).

The NIC is in the switchdev mode, my test-pods are up and running and additional interface is added to the pod and to the OVS bridge.

```
$ kubectl exec -it ovs-offload-pod1 -- ip a
...
68: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 56:ab:a3:33:de:d9 brd ff:ff:ff:ff:ff:ff

$ ovs-vsctl show
4fe27e65-c7e7-4a35-a62a-2b508fa9f6c2
    Bridge br-sriov0
        Port ens802f0_1
            tag: 10
            Interface ens802f0_1
        Port ens802f0_0
            tag: 10
            Interface ens802f0_0
        Port br-sriov0
            Interface br-sriov0
                type: internal
    ovs_version: "2.15.0"
```

What I don't quite get is the command:

kubectl exec -it ovs-offload-pod2 -- iperf3 -c **192.168.1.17** -t 100

The question is, where did this IP address come from? As you can see, the `net1` in my pod does not have any IP address. Should it be added by Multus? But the network attachment definition in the doc does not contain any IPAM or anything. Or maybe should it be set manually inside the pod? I've tried to set that on the host, but the IP address is not propagated to the container.

So, it is possible, that I could get some additional clarification on this?

**Comment by pliurh** [comment]
The ovs cni itself wouldn't do any IPAM to the pod. So if you can either create a net-att-def CR that invokes other [IPAM cni](https://github.com/k8snetworkplumbingwg/ovs-cni/blob/e5fc68ffcc13b436d46e80c1b2e5305b10826c8b/docs/demo.md#configure-ip-address), or manually set the IP in the pod.

**Comment by ipatrykx** [comment]
HI @pliurh , thank you, adding ipam like below solved the issue. Will create PR on this to make the example a bit more straightforward

```
"ipam": {
          "type": "host-local",
          "ranges": [
              [ {
                  "subnet": "192.168.1.0/24",
                  "rangeStart": "192.168.1.10",
                  "rangeEnd": "192.168.1.50",
                  "gateway": "192.168.1.254"
              } ]
          ]
      }
```

Still, not sure why my machine freezes when I apply SriovNetworkNodePolicy with eSwitchMode: switchdev, but will try to debug that. Anyway, closing the issue for now. Thanks!

**Comment by zshi-redhat** [comment]
> Hi, so currently I'm tying to to set the OVS HW offloading up using [this instruction](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/ovs-hw-offload.md).
> 
> The NIC is in the switchdev mode, my test-pods are up and running and additional interface is added to the pod and to the OVS bridge.

@ipatrykx 

FYI, the ovs hwol is supposed to be used with CNI plugins that support this feature. As of now, I think only two CNI plugins have support: ovs-cni, ovn-kubernetes. Sriov-cni doesn't.
I'm not familiar with how ovs-cni is used with ovs hwol, but for ovn-kubernetes, only pod default interface can be used for ovs hwol.
