### ISSUE TITLE
Parallelize the SRIOV configuration on multiple nodes 

### ISSUE THREAD

**Issue by pliurh** [k8snetworkplumbingwg/sriov-network-operator#226]
Currently, when we want to configure the SRIOV on multiple nodes, it is executed in sequence, other nodes wait while one node is being configured. And due to the node draining and reboot, it will take quite a long time, if we have a large number of nodes that need to be configured.

To resolve this issue, we may need to figure out how we can parallelize the configuration on multiple nodes. One idea is to introduce a maximum unavailable number of nodes concept. So that we can conduct the SRIOV configuration simultaneously on such an unavailable number of nodes. We may want to learn the implementation from the Machine Config Operator.

**Comment by SchSeba** [comment]
should be fixed via https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/555

**Comment by SchSeba** [comment]
the PR is merged closing this one
