### ISSUE TITLE
go-get-tool Makefile target to use go install command

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-operator#231]
using `go get` to install go executable is depreated since 1.17 and will be removed in 1.18[1]

we should fix go-get-tool Makefile target before updating to go 1.18

[1]https://go.dev/doc/go-get-install-deprecation

A trivial fix of running `GOFLAGS="" go install` seems to solve the issue for controller-gen but we seem to hit the following issue when trying to install kustomize:

```
# make V=1 kustomize
go: creating new go.mod: module tmp                                                                                                                           
Downloading sigs.k8s.io/kustomize/kustomize/v3@v3.8.7                                                                                                         
go install sigs.k8s.io/kustomize/kustomize/v3@v3.8.7: sigs.k8s.io/kustomize/kustomize/v3@v3.8.7                                                               
        The go.mod file for the module providing named packages contains one or                                                                               
        more exclude directives. It must not contain directives that would cause                                                                              
        it to be interpreted differently than if it were the main module.                                                                                     
make: *** [Makefile:153: kustomize] Error 1
```

**Comment by adrianchiris** [comment]
@e0ne encountered this while working on PR #228

**Comment by zeeke** [comment]
It seems to be fixed in v4 (https://github.com/kubernetes-sigs/kustomize/pull/4387) and discussed in https://github.com/kubernetes-sigs/kustomize/issues/3618 .
Without a backport, upgrading to go1.18 implies upgrading kustomize to v4.

**Comment by SchSeba** [comment]
Hi @zeeke can we close this one now as right now we use golang 1.17?

**Comment by zeeke** [comment]
That's ok from my side. We will tackle it when we'll upgrade to 1.18
