### ISSUE TITLE
Pod creation failed using Sriov network with new SRIOV NICs

### ISSUE THREAD

**Issue by krjagan** [k8snetworkplumbingwg/sriov-network-operator#242]
We are trying to validate Marvell card in Sriov operator using the helm chart. Before executing the helm command, I have updated Marvell card details in configmap.( Qlogic_qede_QL45000_50G: 1077 1654 1664).

https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/deployment/sriov-network-operator/templates/configmap.yaml

After execution of helm command, operator and config-daemon pods are running successfully but while trying to create pod using sriov network, its getting failed.

1) Deploy SR-IOV Network Operator
      # Install Operator
      $ helm install -n sriov-network-operator --create-namespace --wait sriov-network-operator ./
2) Created SriovNetworkNodePolicy
3) Created SriovNetwork

NAME                                          READY   STATUS              RESTARTS   AGE
pod/samplepod                                 0/1     ContainerCreating   0          4h53m
pod/sriov-device-plugin-z95fc                 1/1     Running             0          130m
pod/sriov-network-config-daemon-xg9v7         3/3     Running             3          139m
pod/sriov-network-operator-6567584db9-t9gkh   1/1     Running             0          6h33m

NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                 AGE
daemonset.apps/sriov-device-plugin           1         1         1       1            1           beta.kubernetes.io/os=linux,node-role.kubernetes.io/worker=   6h25m
daemonset.apps/sriov-network-config-daemon   1         1         1       1            1           beta.kubernetes.io/os=linux,node-role.kubernetes.io/worker=   6h33m

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sriov-network-operator   1/1     1            1           6h33m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/sriov-network-operator-6567584db9   1         1         1       6h33m

nodestates:-

Allocatable:
  cpu:                       39600m
  ephemeral-storage:         92115Mi
  hugepages-1Gi:             0
  hugepages-2Mi:             0
  memory:                    127548123855
  openshift.io/marvellnics:  3
  pods:                      110

VF status on node:-

 status:
    interfaces:
    - Vfs:
      - deviceID: "1664"
        driver: qede
        mac: 9a:c0:0e:90:15:01
        mtu: 1500
        name: ens3f0v0
        pciAddress: "0000:37:02.0"
        vendor: "1077"
        vfID: 0

pod logs:-

**Warning  FailedCreatePodSandBox  12m (x874 over 4h3m)     kubelet  (combined from similar events): Failed to create pod sandbox: rpc error: code = Unknown desc = [failed to set up sandbox container "b821ee49cbea3bef6dd2fbcd92798dd4ea3e256b39ad79a23d01dbaf7bdf3765" network for pod "samplepod": networkPlugin cni failed to set up pod "samplepod_sriov-network-operator" network: Multus: [sriov-network-operator/samplepod/]: error getting pod: Get "https://[12.233.0.1]:443/api/v1/namespaces/sriov-network-operator/pods/samplepod?timeout=1m0s": dial tcp 12.233.0.1:443: i/o timeout, failed to clean up sandbox container "b821ee49cbea3bef6dd2fbcd92798dd4ea3e256b39ad79a23d01dbaf7bdf3765" network for pod "samplepod": networkPlugin cni failed to teardown pod "samplepod_sriov-network-operator" network: Multus: [sriov-network-operator/samplepod/]: error getting pod: Get "https://[12.233.0.1]:443/api/v1/namespaces/sriov-network-operator/pods/samplepod?timeout=1m0s": dial tcp 12.233.0.1:443: i/o timeout]**

Please help me out with this issue... Thank you in advance

**Comment by adrianchiris** [comment]
i see : `Get "https://[12.233.0.1]:443/api/v1/namespaces/sriov-network-operator/pods/samplepod?timeout=1m0s": dial tcp 12.233.0.1:443: i/o timeout]` are you able to access kubernetes API with this address ?

seems like multus failed to access k8s API server.

**Comment by krjagan** [comment]
Hi adrianchiris,

Thank you for your response...

To test multus cni, I have created macvlan network then deployed a sample pod and assgined macvlan with the help of multus successfully but i'm getting error while using sriov network.

**Comment by krjagan** [comment]
please find the below sriov logs 

sriov-device-plugin:-

I0207 19:24:49.249678       1 manager.go:51] Using Kubelet Plugin Registry Mode
I0207 19:24:49.249718       1 main.go:44] resource manager reading configs
I0207 19:24:49.249823       1 manager.go:79] raw ResourceList: {"resourceList":[{"resourceName":"marvellnics","selectors":{"vendors":["1077"],"devices":["1664"],"rootDevices":["0000:37:00.0"],"IsRdma":false,"NeedVhostNet":false},"SelectorObj":null}]}
I0207 19:24:49.249916       1 factory.go:166] net device selector for resource marvellnics is &{DeviceSelectors:{Vendors:[1077] Devices:[1664] Drivers:[] PciAddresses:[]} PfNames:[] RootDevices:[0000:37:00.0] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I0207 19:24:49.249932       1 manager.go:99] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:marvellnics DeviceType:netDevice Selectors:0xc00012ed20 SelectorObj:0xc000264f70}]
I0207 19:24:49.249959       1 manager.go:200] validating resource name "marvell.com/marvellnics"
I0207 19:24:49.249964       1 main.go:60] Discovering host devices
I0207 19:24:49.297072       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:37:00.0 02              QLogic Corp.            FastLinQ QL45000 Series 50GbE Controller
I0207 19:24:49.297557       1 netDeviceProvider.go:123] excluding interface ens3f0:  default route found: {Ifindex: 2 Dst: <nil> Src: <nil> Gw: 10.0.0.1 Flags: [] Table: 254 Realm: 0}
I0207 19:24:49.297619       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:37:00.1 02              QLogic Corp.            FastLinQ QL45000 Series 50GbE Controller
I0207 19:24:49.298112       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:37:02.0 02              QLogic Corp.            FastLinQ QL45000 Series Gigabit Ether...
I0207 19:24:49.298435       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:37:02.1 02              QLogic Corp.            FastLinQ QL45000 Series Gigabit Ether...
I0207 19:24:49.298640       1 netDeviceProvider.go:84] netdevice AddTargetDevices(): device found: 0000:37:02.2 02              QLogic Corp.            FastLinQ QL45000 Series Gigabit Ether...
I0207 19:24:49.298869       1 main.go:66] Initializing resource servers
I0207 19:24:49.298892       1 manager.go:105] number of config: 1
I0207 19:24:49.298901       1 manager.go:109]
I0207 19:24:49.298906       1 manager.go:110] Creating new ResourcePool: marvellnics
I0207 19:24:49.298913       1 manager.go:111] DeviceType: netDevice
I0207 19:24:49.299653       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:37:00.1. <nil>
I0207 19:24:49.300261       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:37:02.0. <nil>
I0207 19:24:49.300692       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:37:02.1. <nil>
I0207 19:24:49.301155       1 utils.go:71] Devlink query for eswitch mode is not supported for device 0000:37:02.2. <nil>
I0207 19:24:49.301263       1 factory.go:106] device added: [pciAddr: 0000:37:02.0, vendor: 1077, device: 1664, driver: qede]
I0207 19:24:49.301270       1 factory.go:106] device added: [pciAddr: 0000:37:02.1, vendor: 1077, device: 1664, driver: qede]
I0207 19:24:49.301273       1 factory.go:106] device added: [pciAddr: 0000:37:02.2, vendor: 1077, device: 1664, driver: qede]
I0207 19:24:49.301290       1 manager.go:139] New resource server is created for marvellnics ResourcePool
I0207 19:24:49.301297       1 main.go:72] Starting all servers...
I0207 19:24:49.301707       1 server.go:199] starting marvellnics device plugin endpoint at: marvell.com_marvellnics.sock
I0207 19:24:49.302562       1 server.go:226] marvellnics device plugin endpoint started serving
I0207 19:24:49.302601       1 main.go:77] All servers started.
I0207 19:24:49.302607       1 main.go:78] Listening for term signals
I0207 19:24:49.641368       1 server.go:110] Plugin: marvell.com_marvellnics.sock gets registered successfully at Kubelet
I0207 19:24:49.641405       1 server.go:134] ListAndWatch(marvellnics) invoked
I0207 19:24:49.641420       1 server.go:142] ListAndWatch(marvellnics): send devices &ListAndWatchResponse{Devices:[]*Device{&Device{ID:0000:37:02.2,Health:Healthy,Topology:&TopologyInfo{Nodes:[]*NUMANode{&NUMANode{ID:0,},},},},&Device{ID:0000:37:02.0,Health:Healthy,Topology:&TopologyIn

sriov pod logs 

Type     Reason                  Age                From               Message
  ----     ------                  ----               ----               -------
  Normal   Scheduled               24s                default-scheduler  Successfully assigned sriov-network-operator/podtest to worker.jagan.local
  Warning  FailedCreatePodSandBox  26s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "79be8238c180eb4a3cda9b2f87c0cea62e41924c4a22e61f94ce8071a43295b5" network for pod "podtest": networkPlugin cni failed to set up pod "podtest_sriov-network-operator" network: Multus: [sriov-network-operator/podtest/]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: failed to get a ResourceClient instance: getKubeletClient: error getting pod resources from client: getPodResources: failed to list pod resources, &{0xc0000f4a80}.Get(_) = _, rpc error: code = Unimplemented desc = unknown service v1.PodResourcesLister
  Warning  FailedCreatePodSandBox  24s                kubelet            Failed to create pod sandbox: rpc error: code = Unknown desc = failed to set up sandbox container "d827da37e0c99ff1e5ab7102efbd9a832362e3851a0e33c140fac1aabb63a9ac" network for pod "podtest": networkPlugin cni failed to set up pod "podtest_sriov-network-operator" network: Multus: [sriov-network-operator/podtest/]: error loading k8s delegates k8s args: TryLoadPodDelegates: error in getting k8s network for pod: GetNetworkDelegates: failed getting the delegate: getKubernetesDelegate: failed to get a ResourceClient instance: getKubeletClient: error getting pod resources from client: getPodResources: failed to list pod resources, &{0xc0002da700}.Get(_) = _, rpc error: code = Unimplemented desc = unknown service v1.PodResourcesLister

Please help me out with this issue....

**Comment by adrianchiris** [comment]
hmm. perhaps related to : https://github.com/k8snetworkplumbingwg/multus-cni/issues/717

what is your k8s and multus-cni versions ?

**Comment by krjagan** [comment]
Hi Adrian Chris,

I have tested Marvell (**Qlogic_qede_QL45000_50G: 1077 1654 16640**) card in two versions of K8s cluster (v1.19 & v1.23) using SRIOV operator-based.

Now I'm trying to validate vendor card using **hack/run-e2e-test-kind.sh** script with **system-service** but geeting error.

**docker build -t sriov-network-operator:latest -f /root/sriov-network-operator/Dockerfile /root/sriov-network-operator
Sending build context to Docker daemon 191.5 MB
Step 1/9 : FROM golang:1.17 AS builder
Error parsing reference: "golang:1.17 AS builder" is not a valid repository/tag: invalid reference format
Exit code: '1'. Sleeping '10' seconds before retrying
docker build -t sriov-network-operator:latest -f /root/sriov-network-operator/Dockerfile /root/sriov-network-operator
Sending build context to Docker daemon 191.5 MB
Step 1/9 : FROM golang:1.17 AS builder
Error parsing reference: "golang:1.17 AS builder" is not a valid repository/tag: invalid reference format**

Please provide the process of validating cards.
