### ISSUE TITLE
sriovnetworknodestates for node shows "operation not supported" at the end when the port is IB

### ISSUE THREAD

**Issue by cumulus-joeyyang** [k8snetworkplumbingwg/sriov-network-operator#265]
Hi team,

I tried to use ib interface for SRIOV and managed to apply the following SriovNetoworkNodePolicy:
# cat 03-SriovNetworkNodePolicy-IB.yaml                                                                   
apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
  name: nodepolicy-mlnxib
  namespace: sriov-network-operator
spec:
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  resourceName: mlnxVFIB
  priority: 99
  mtu: 4000
  numVfs: 8
  nicSelector:
    vendor: "15b3"
    deviceID: "101b"
    pfNames: ["ib0"]
  isRdma: true
  linkType: ib

After that I can see the sriovnetworknodestates of a node shows VF but the end of the output is:
...
  lastSyncError: operation not supported
  syncStatus: InProgress
...

Then I read the logs of container sriov-network-config-daemon, it's not clear to me where the problem is.
I'm attaching the output here. thanks.
[ib sriov network operator show.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/8260404/ib.sriov.network.operator.show.txt)

**Comment by weight-loss666** [comment]
The above error is finally located in: /vendor/github.com/vishvananda/netlink/link_linux.go

// LinkSetVfNodeGUID sets the node GUID of a vf for the link.
// Equivalent to: `ip link set dev $link vf $vf node_guid $nodeguid`
func LinkSetVfNodeGUID(link Link, vf int, nodeguid net.HardwareAddr) error {
	return pkgHandle.LinkSetVfGUID(link, vf, nodeguid, nl.IFLA_VF_IB_NODE_GUID)
}

// LinkSetVfPortGUID sets the port GUID of a vf for the link.
// Equivalent to: `ip link set dev $link vf $vf port_guid $portguid`
func LinkSetVfPortGUID(link Link, vf int, portguid net.HardwareAddr) error {
	return pkgHandle.LinkSetVfGUID(link, vf, portguid, nl.IFLA_VF_IB_PORT_GUID)
}
ip link set dev $link vf $vf node_guid $nodeguid
The above commands need to be supported by a sufficiently high system kernel version.
I upgrade my kernel to 4.18 and solved it.

**Comment by SchSeba** [comment]
@weight-loss666 thanks for the update!

I will close the issue now
