### ISSUE TITLE
Add ResourcePrefix to SriovOperatorConfig CRD

### ISSUE THREAD

**Issue by rollandf** [k8snetworkplumbingwg/sriov-network-operator#272]
Currently, the Resource Prefix can be change only by an env variable in the Operator deployment. If the operator is deployed by OLM, changing its value is not simple.

I suggest to have the possibility to configure it via `SriovOperatorConfig` CRD as an optional configuration.
If it will not be present, the logic will be as today, use the env var `RESOURCE_PREFIX`.

**Comment by SchSeba** [comment]
is there a special reason why the env var doesn't handle your use-case?

**Comment by e0ne** [comment]
@SchSeba how can we set this variable during deployment with OLM in OpehShift?

**Comment by SchSeba** [comment]
Hi @e0ne with the OLM in Openshift is not possible to change this as intended.

In general, OLM is an opinionated deployment for an operator.
is the same reason why you can't add the DEV variable when deploying the operator using OLM (https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/252#issuecomment-1073281419)

In general I think we should change the default one on this repo to be something that represents this upstream work.

another point if needed is to publish the operator (from this repo) to the operatorHub
