### ISSUE TITLE
SriovNetworkNodeState temporary state cause unneeded plugins actions

### ISSUE THREAD

**Issue by rollandf** [k8snetworkplumbingwg/sriov-network-operator#283]
There is a stage when the SriovNetworkNodeState is initializing where the spec is empty because the SriovNetworkNodePolicyReconciler did not yet applied the policies.

It can cause a non required action by the plugins, that will try to apply the empty spec by resetting the NIC for example.

The flow currently is:
1 Creation of NodeState by NodePolicyController ( no policies applied at this state, as Interfaces are not present yet)
2 Status update with Interfaces by NodeStateStatusWriter 
3 Spec Update by NodePolicyController
4 Plugin action based on spec

Now, the plugins are also triggered between 2 and 3, causing unneeded configuration.

There is a need to be able to know if the empty spec is intentional or just a temporary state.

**Comment by SchSeba** [comment]
The fix is in place closing this issue
