### ISSUE TITLE
Add golangci-lint target

### ISSUE THREAD

**Issue by rollandf** [k8snetworkplumbingwg/sriov-network-operator#288]
For better lint, add golangci-lint tool to project

**Comment by adrianchiris** [comment]
+1 on this

we can reference from sriov-network-device-plugin

GA:
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/58eb3660dcaeec068c8c8878825c6d724020966a/.github/workflows/build-test-lint.yml#L45

adding a .golangci.yaml for linter config
https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/58eb3660dcaeec068c8c8878825c6d724020966a/.github/workflows/build-test-lint.yml#L45


and makefile target
https://github.com/Mellanox/rdma-cni/blob/b013003eae5344065fa47699aecde4a733234faa/Makefile#L81

**Comment by SchSeba** [comment]
@rollandf can we close this one or we are still missing some features?

**Comment by rollandf** [comment]
We can close it. There are still linters that are commented out, but we can handle them without this issue.
