### ISSUE TITLE
Reject SriovNetworkNodePolicy with bad resourceName

### ISSUE THREAD

**Issue by zeeke** [k8snetworkplumbingwg/sriov-network-operator#294]
`SriovNetworkNodePolicy.Spec.ResourceName` field is used as k8s resource name and it is passed to the sriov-network-device-plugin. If the user provides a [bad value](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/5c77c77a26260ebf48275012f000b3e9c0260409/pkg/utils/utils.go#L268) for this field, eg a name-with-dashes, the resource creation goes well but the device plugin complains in the logs:

```
I0429 07:26:52.803352       1 factory.go:166] net device selector for resource sriovnic-bad-name-resource is &{DeviceSelectors:{Vendors:[] Devices:[] Drivers:[] PciAddresses:[]} PfNames:[eno1] RootDevices:[] LinkTypes:[] DDPProfiles:[] IsRdma:false NeedVhostNet:false}
I0429 07:26:52.803365       1 manager.go:99] unmarshalled ResourceList: [{ResourcePrefix: ResourceName:sriovnic-multi-networkpolicy-resource DeviceType:netDevice Selectors:0xc00000ed38 SelectorObj:0xc0003395f0}]
E0429 07:26:52.803396       1 manager.go:188] resource name "sriovnic-bad-name-resource" contains invalid characters
F0429 07:26:52.803402       1 main.go:57] Exiting.. one or more invalid configuration(s) given
```

It could be useful to get this error message during the resource creation, so it would be clearer to the user where the problem is.

**Comment by SchSeba** [comment]
Hi we have this one in place (https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/cebbdb3c4c17caa11afad05d6fc98f54a81bbb7c/pkg/webhook/validate.go#L88)

so when the user apply the sriovNetworkNodePolicy it should failed

**Comment by zeeke** [comment]
I tested again and I got:

```
admission webhook \"operator-webhook.sriovnetwork.openshift.io\" denied the request: resource name \"bad-name-one\" contains invalid characters, the accepted syntax of the regular expressions is: \"^[a-zA-Z0-9_]+$\"
```

My previous test was probably with `enableOperatorWebhook: false`

I'm closing this issue
