### ISSUE TITLE
Mellanox ConnectX‑6 Lx: trying  mstconfig which is not supported on 6th gen devices 

### ISSUE THREAD

**Issue by krypto935** [k8snetworkplumbingwg/sriov-network-operator#317]
Hi Team,
I have a Mellanox Connectx-6 LX device which i am trying to configure through sriov-network-operator,but it fails to sync with error Failed.

_**RunCommand(): mstconfig [-e -d 0000:18:00.0 q]
I0607 15:07:30.460717  124588 utils.go:706] RunCommand(): mstconfig, [-e -d 0000:18:00.0 q]
I0607 15:07:30.467921  124588 utils.go:708] RunCommand(): -E- Failed to open the device
, exit status 3**_

I am not sure why the image tries to execute mstconfig as per mstconfig help page it says it supports only Gen 4 and Gen 5.

**kubectl get sriovnetworknodestates -n sriov-network-operator pulab-1 -o yaml|grep -i syncStatus
  syncStatus: InProgress**
  
  in few seconds
  
 **kubectl get sriovnetworknodestates -n sriov-network-operator pulab-1 -o yaml|grep -i syncStatus
  syncStatus: Failed**
  
  
**kubectl get po -n sriov-network-operator
NAME                                     READY   STATUS    RESTARTS      AGE
sriov-device-plugin-q989n                1/1     Running   0             64m
sriov-device-plugin-sqsc2                1/1     Running   1 (26m ago)   64m
sriov-network-config-daemon-6r625        3/3     Running   0             94m
sriov-network-config-daemon-vrpns        3/3     Running   3 (26m ago)   94m
sriov-network-operator-98db5fcbf-2s4dn   1/1     Running   0             3h20m**

**_lspci -vvv|grep -i ethernet
18:00.0 Ethernet controller: Mellanox Technologies MT2894 Family [ConnectX-6 Lx]
18:00.1 Ethernet controller: Mellanox Technologies MT2894 Family [ConnectX-6 Lx]
8a:00.0 Ethernet controller: Mellanox Technologies MT2894 Family [ConnectX-6 Lx]
8a:00.1 Ethernet controller: Mellanox Technologies MT2894 Family [ConnectX-6 Lx]_**

Container image: https://github.com/k8snetworkplumbingwg/sriov-cni/pkgs/container/sriov-cni/10789280?tag=faf2d00749483f330c94ca1e0faee5c35f41bbe8

Logs from container:

**_kubectl logs -n sriov-network-operator sriov-network-config-daemon-vrpns sriov-network-config-daemon_**

[mellanox-error.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/8854442/mellanox-error.txt)

**Comment by adrianchiris** [comment]
can you run config daemon container via docker (execute into shell) using host network and run : `mstconfig -e -d 0000:18:00.0 q`

> I am not sure why the image tries to execute mstconfig as per mstconfig help page it says it supports only Gen 4 and Gen 5

message is a bit cryptic but ConnectX6 Lx is regarded as "gen 5" from mstconfig POV

**Comment by krypto935** [comment]
Thanks @adrianchiris  for your reply. This is what i see from the image,it shows only up to connectx5 .
Also i could see that ConnectX6 Lx is not listed in the supported hardware matrix,is that the reason?

https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/supported-hardware.md

docker exec -ti test1 mstconfig|tail
        To set configuration               : mstconfig -d 04:00.0 set SRIOV_EN=1 NUM_OF_VFS=16 WOL_MAGIC_EN_P1=1
        To set raw configuration           : mstconfig -d 05:00.0 -f conf_file set_raw
        To reset configuration             : mstconfig -d 04:00.0 reset

    Supported devices:
        4th Generation devices: ConnectX3, ConnectX3-Pro (FW 2.31.5000 and above).
        5th Generation devices: ConnectIB, ConnectX4, ConnectX4-LX, ConnectX5.

    Note: query device to view supported configurations by Firmware.

**Comment by adrianchiris** [comment]
Yes, ConnectX6 Lx currently is not supported.

there are two main items i believe:

1. need to bump mstflint version to one that supports connectx6 Lx (4.20) which i am not sure is available in centos8 stream repo
2. Test sriov network operator with  ConnectX6 LX and add it to supporterd hardware list in the operator.

**Comment by adrianchiris** [comment]
Are you running with latest version of sriov-network operator ? sriov network operator should not handle un-supported devices unless otherwise specified. 

did you edit the supported devices config map[1] ? or ran sriov config daemon in DEV_MODE ?

if the answer is no to both, and you are running with latest sriov network operator image then there might be a bug.


[1] https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/deploy/configmap.yaml
[2] https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/hacking.md#enable-unsupported-nics

**Comment by Ananth-vr** [comment]
@adrianchiris i have changed the image to latest build and now it throws an error saying its an un supported device.I wasnt using the latest image. 
Can i know when would connectX6 Lx will be supported without any of these changes.

**Comment by adrianchiris** [comment]
ATM no ETA for adding support for it.

The project is Opensource so PR is welcome :)

Id start from opening an issue requesting to add support for it.

**Comment by Ananth-vr** [comment]
Thanks again for your quick reply.For now i will try to modify CM and check if it helps.

i find this interesting, just checked openshift which uses sriov-network-operator as well but supports 6X LX from at   least a year ;)

https://docs.openshift.com/container-platform/4.9/networking/hardware_networks/about-sriov.html#supported-devices_about-sriov

**Comment by krypto935** [comment]
thanks @SchSeba it works

**Comment by adrianchiris** [comment]
yes it is possible.

**Comment by SchSeba** [comment]
Fixed by: https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/358
