### ISSUE TITLE
why not add a target for install operator-sdk in Makefile

### ISSUE THREAD

**Issue by zhaowei413** [k8snetworkplumbingwg/sriov-network-operator#319]
As list in this Makefile， it will use operator-sdk to generate code and manifests, why not  add a target for install operator-sdk which treated as dependence for target "bundle"。
This enables automatic operator-sdk installation instead of manual installation as described in the documentation. It's a lot more convenient.

https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/Makefile

**Comment by SchSeba** [comment]
Hi @zhaowei413 you are more then welcome to open a PR

**Comment by SchSeba** [comment]
we removed the make bundle from the repo as we only support helm in the project.
the bundle is done for openshift in the sync repo under https://github.com/openshift/sriov-network-operator/

closing this one
