### ISSUE TITLE
SRIOV Network Operator Release

### ISSUE THREAD

**Issue by Eoghan1232** [k8snetworkplumbingwg/sriov-network-operator#324]
It's been a while since our last release
SRIOV Network Operator's latest release doesn't work with K8s 1.24
We have merged the changes to make it compatible, can we look to create a minor release?

**Comment by Eoghan1232** [comment]
Now that #321 is merged. 
Are there any other PR's we want to be merged before releasing a new version of Network Operator?
@adrianchiris @SchSeba

**Comment by mariuszprzysiezniuk** [comment]
I have a question regarding images used in SRIOV Network Operator.

Right now it uses images built on quay openshift repo https://github.com/openshift/sriov-network-operator: https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/b876ce53081606260cee8ed66046f7bd1e035677/hack/env.sh#L7.
So regardless of those changes, SRIOV Network Operator still won't fully work.

Shouldn't those envs be changed to values from https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/deployment/sriov-network-operator/values.yaml#L31 to use images built from this repository?

Objects definitions are also duplicated:
https://github.com/k8snetworkplumbingwg/sriov-network-operator/tree/master/deploy
https://github.com/k8snetworkplumbingwg/sriov-network-operator/tree/master/deployment/sriov-network-operator/templates
Makefile uses hack/deploy-setup.sh which builts operator from the first option

**Comment by adrianchiris** [comment]
> Right now it uses images built on quay openshift repo https://github.com/openshift/sriov-network-operator:

+1 on updating Makefile and related files to deploy components from k8snetworkplumbingwg and not alternate repos.

> Objects definitions are also duplicated

that is correct. currently for dev env you could use the first option to deploy the operator via makefile.
some tweaks will be needed as you mentioned in `hack/env.sh`

an alternative is to use helm chart which deploys all related components from upstream. this is more suitable for an end user to consume.

the chart in the master branch is set to deploy latest images so it does not have specific version set.
as part of the release, helm package is generated for the release and uploaded as release artifact.
(this chart should have the correct versions set).


see : https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/download/v1.1.0/sriov-network-operator-1.1.0.tgz
in : https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.1.0

as an example.

**Comment by Eoghan1232** [comment]
> > Right now it uses images built on quay openshift repo https://github.com/openshift/sriov-network-operator:
> 
> +1 on updating Makefile and related files to deploy components from k8snetworkplumbingwg and not alternate repos.

+1

**Comment by SchSeba** [comment]
+1 we should update the Makefile to point to this repo images

**Comment by Eoghan1232** [comment]
@adrianchiris 
@SchSeba 

Are there any other PR's you want merged before next release? 
I would like to get the release out today/tomorrow.

**Comment by adrianchiris** [comment]
my wish list:

- #287 
- #312 
- #323

**Comment by Eoghan1232** [comment]
> This can be great. The problem is I am not sure we will be able to merge all of them today/tomorrow timeframe

Can postpone until end of week, no problem.

**Comment by Eoghan1232** [comment]
Proposed to release the dependent repos aswell:

[sriov-cni](https://github.com/k8snetworkplumbingwg/sriov-cni/releases) last release was v2.6.2 Nov 09, 21. I want to release this, golang 1.18 and k8s 1.24 were merged. 
[ib-sriov-cni](https://github.com/k8snetworkplumbingwg/ib-sriov-cni/releases) last release was v1.0.2 Nov 09, 21. Don't think we need to release again. WDYT? 
[sriov-network-device-plugin](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/releases) last release was V3.5.0 May 26, 22. This was bumped to golang 1.18 and K8s 1.24, I think we should release again.
[network-resource-injector](https://github.com/k8snetworkplumbingwg/network-resources-injector/releases) last release was v1.3 Nov 28, 21. I want to release this, golang 1.18 and k8s 1.24 were merged.

I do not see any major PR's in each repo to be merged.
I would like this one in [sriov-cni #205](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/205) to be merged (pending another review)

Do we want this one also? In Network Resource Injector: (I think skip for this release, WDYT?)
[health check #125](https://github.com/k8snetworkplumbingwg/network-resources-injector/pull/125)

@adrianchiris @SchSeba @e0ne WDYT?

**Comment by adrianchiris** [comment]
+1

**Comment by eoghanlawless** [comment]
@adrianchiris @SchSeba @e0ne

I'll be releasing sriov-network-operator by EOD today 17:00 GMT

Will I be releasing any of the dependent repos mentioned in the comment above?

Are we okay to release without these merged?
- #287
- k8snetworkplumbingwg/sriov-cni#205
- k8snetworkplumbingwg/network-resources-injector#125

**Comment by adrianchiris** [comment]
> Are we okay to release without these merged?

Yes from my side

**Comment by eoghanlawless** [comment]
Released: https://github.com/k8snetworkplumbingwg/sriov-network-operator/releases/tag/v1.2.0

**Comment by SchSeba** [comment]
@eoghanlawless can we close this issue?
