### ISSUE TITLE
Is DPDK supported by the sriov-network-operator plugin.

### ISSUE THREAD

**Issue by ognjen011** [k8snetworkplumbingwg/sriov-network-operator#347]
I am running rancher with sriov-network-operator plugin. Can someone just comment am i able to use this plugin to run DPDK pods in the environment? I was successful running SRIOV setup but i tried many options for the DPDK pods and they never seem to be able to communicate when the interface is attached to the pod.

**Comment by SchSeba** [comment]
you can see the list here https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/doc/supported-hardware.md#supported-features-per-hardware

If the nic you are using is supported in the list but it still doesn't work you will need to add more info to this issue

**Comment by ognjen011** [comment]
Ok the cards seem supported correct me if am wrong here.  I m running MT2892 Family [ConnectX-6 Dx] and Ethernet Controller E810-C for QSFP 1592.  I have a node policy that enable deviceType: vfio-pci and the interfaces are listed below the dpdk compatible  driver 

Network devices using DPDK-compatible driver
============================================
0000:b2:01.0 'Ethernet Adaptive Virtual Function 1889' drv=vfio-pci unused=iavf,uio_pci_generic
0000:b2:01.1 'Ethernet Adaptive Virtual Function 1889' drv=vfio-pci unused=iavf,uio_pci_generic
0000:b2:01.2 'Ethernet Adaptive Virtual Function 1889' drv=vfio-pci unused=iavf,uio_pci_generic
0000:b2:01.3 'Ethernet Adaptive Virtual Function 1889' drv=vfio-pci unused=iavf,uio_pci_generic

and another exmple:

Network devices using DPDK-compatible driver
============================================
0000:41:00.2 'ConnectX Family mlx5Gen Virtual Function 101e' if=enp65s0f0v0 drv=mlx5_core unused=vfio-pci,uio_pci_generic 
0000:41:00.3 'ConnectX Family mlx5Gen Virtual Function 101e' if=enp65s0f0v1 drv=mlx5_core unused=vfio-pci,uio_pci_generic 
0000:41:00.4 'ConnectX Family mlx5Gen Virtual Function 101e' if=enp65s0f0v2 drv=mlx5_core unused=vfio-pci,uio_pci_generic 
0000:41:00.5 'ConnectX Family mlx5Gen Virtual Function 101e' if=enp65s0f0v3 drv=mlx5_core unused=vfio-pci,uio_pci_generic 

I am seeing two types of errors. The one type is that pod comes up and i am seeing and error where when second eth1 is assigned to a pod it is unable to ping from the node network range.

The second error i am seeing  that the pod fails to execute PROX which is a basically a traffic generator tool. 

Is there a specific config that i need to have in a network definition file or a node policy itself. Right now the only difference is the deviceType: vfio-pci from the SRIOV setup which is running fine?

**Comment by moshe010** [comment]
To run DPKD on Mellanox NIC you don't need to bind vfio driver, you need mlx5_core. see [1].
To make DPDK work with Mellanox NIC you need mlx5_core [2] and isRDMA flag set to true[3] 

[1] - https://doc.dpdk.org/guides/howto/flow_bifurcation.html#using-flow-bifurcation-on-mellanox-connectx
[2] - https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/docs/dpdk/mlnx-dpdk/configMap.yaml#L16
[3] - https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/master/docs/dpdk/mlnx-dpdk/configMap.yaml#L17

**Comment by ognjen011** [comment]
I added below to the node policy:

 deviceType: netdevice
 isRdma: true

I have checked the interfaces are all bound to mlx5_core driver. The secondary interface assigned to he pods is pingable but i am still getting the same error on the pods  testpmd: No probed ethernet devices.  

The reference to the config map is from sriov-network-device-plugin, i am currently running sriov-network-operator plugin. I am a little confused do i need a configMap  as well? The plugin was installed through the rancher as  a helm chart . Does sriov-networ-operator plugin work by itself or do i need another plugin installed such as sriov-network-device-plugin?

**Comment by SchSeba** [comment]
Hi @ognjen011 can you please share a bit more information?

* pod definition
* sriovNetworkNodeState and NodePolicy
* `env` inside the pod

**Comment by ognjen011** [comment]
My setup is the the same as per the documentation 

Node policy:

apiVersion: sriovnetwork.openshift.io/v1
kind: SriovNetworkNodePolicy
metadata:
name: dpdk-mellanox-policy
namespace: cattle-sriov-system
spec:
nicSelector:
deviceID: "101d"
rootDevices:
- 0000:41:00.0
vendor: "15b3"
nodeSelector:
feature.node.kubernetes.io/network-sriov.capable: "true"
numVfs: 64
priority: 90
deviceType: netdevice
resourceName: mlxnics

and network attachment:

apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: dpdknetwork-mellanox
annotations:
k8s.v1.cni.cncf.io/resourceName: rancher.io/mlxnics
spec:
config: '{
"type":"sriov",
"cniVersion": "0.3.1",
"ipam": {
"type": "host-local",
"subnet": "192.168.8.0/24",
"startRange": "192.168.8.50",
"endRange": "192.168.8.200",
"routes": [{
"dst": "0.0.0.0/0"
}],
"gateway": "192.168.8.1"
}
}'

The pod is copied from the the redhat website from their dpdk example:

apiVersion: v1
kind: Pod
metadata:
  name: dpdk-pod
  annotations:
    sriovnetwork.openshift.io/networks: dpdknetwork-mellanox
spec:
  containers:
  - name: dpdk-network-pod
    image: rparikh/dpdk-app-centos
    securityContext:
      privileged: true
       capabilities:
        add: ["IPC_LOCK", "SYS_ADMIN"] 
    volumeMounts:
    - mountPath: /etc/podnetinfo
      name: podnetinfo
      readOnly: false
    - mountPath: /dev/hugepages
      name: hugepage
    resources:
      requests:
        memory: 1Gi
        cpu: "4"
        rancher.io/mlxnics: '1'
      limits:
        hugepages-1Gi: 2Gi
        cpu: "4"
        rancher.io/mlxnics: '1'
    # Uncomment to control which DPDK App is running in container.
    # If not provided, l3fwd is default.
    #   Options: l2fwd l3fwd testpmd
    env:
    - name: DPDK_SAMPLE_APP
      value: "testpmd"
    #
    # Uncomment to debug DPDK App or to run manually to change
    # DPDK command line options.
    command: ["sleep", "infinity"]
  nodeSelector:
    feature.node.kubernetes.io/network-sriov.capable: "true"
  volumes:
  - name: podnetinfo
    downwardAPI:
      items:
        - path: "labels"
          fieldRef:
            fieldPath: metadata.labels
        - path: "annotations"
          fieldRef:
            fieldPath: metadata.annotations
  - name: hugepage
    emptyDir:
      medium: HugePages

env In the pod. I am not too sure exactly what the pod does but when you run the dpdk-app it fails with LPM or EM none selected, default LPM on port 0 is not present on the board (obviously i have made sure i am using the correct network card many, many times over)
EAL: Error - exiting with code: 1
  Cause: check_port_config failed

LANG=en_US.UTF-8
IPERF_SERVER_SERVICE_HOST=10.96.65.7
HOSTNAME=dpdk-mlx
IPERF_SERVER_PORT_5001_TCP_PORT=5001
KUBERNETES_PORT_443_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP_ADDR=10.96.0.1
PCIDEVICE_RANCHER_IO_MLXNICS=0000:41:05.5
KUBERNETES_PORT=tcp://10.96.0.1:443
PWD=/
HOME=/root
IPERF_SERVER_SERVICE_PORT=5001
IPERF_SERVER_PORT_5001_TCP_ADDR=10.96.65.7
KUBERNETES_SERVICE_PORT_HTTPS=443
IPERF_SERVER_PORT=tcp://10.96.65.7:5001
KUBERNETES_PORT_443_TCP_PORT=443
DPDK_SAMPLE_APP=testpmd
IPERF_SERVER_PORT_5001_TCP_PROTO=tcp
KUBERNETES_PORT_443_TCP=tcp://10.96.0.1:443
TERM=xterm
SHLVL=1
KUBERNETES_SERVICE_PORT=443
PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
KUBERNETES_SERVICE_HOST=10.96.0.1
IPERF_SERVER_PORT_5001_TCP=tcp://10.96.65.7:5001
LESSOPEN=||/usr/bin/lesspipe.sh %s
_=/usr/bin/env

**Comment by adrianchiris** [comment]
you should set `isRdma` to `true` in `SriovNetworkNodePolicy`

in the dpdk pod:

1. do you see any char devices under `/dev/infiniband` ? 
2. what is the output of:
`ip link show`
`ip address show`

**Comment by ognjen011** [comment]
isRdma is set to true it was a typo when i copied it. I always end up with the same result. The pod info looks like this 

For the /dev/infiniband i see bunch of issm uverbs and umad files.

ip link show 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
3: eth0@if89: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP mode DEFAULT group default 
    link/ether ba:fa:9c:95:2d:33 brd ff:ff:ff:ff:ff:ff link-netnsid 0
54: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP mode DEFAULT group default qlen 1000
    link/ether 22:65:b5:05:57:1d brd ff:ff:ff:ff:ff:ff

ip address show

1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
3: eth0@if89: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether ba:fa:9c:95:2d:33 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.14.208.50/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b8fa:9cff:fe95:2d33/64 scope link 
       valid_lft forever preferred_lft forever
54: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 22:65:b5:05:57:1d brd ff:ff:ff:ff:ff:ff
    inet 192.168.8.51/24 brd 172.16.47.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::2065:b5ff:fe05:571d/64 scope link 
       valid_lft forever preferred_lft forever

**Comment by adrianchiris** [comment]
looks OK IMO.

i would double check that you pass the assigned PCI device to the dpdk app device whitelist.

e.g
`PCIDEVICE_RANCHER_IO_MLXNICS=0000:41:05.5`

**Comment by ognjen011** [comment]
Ok i checked that as well it seems fine 

PCIDEVICE_RANCHER_IO_MLXNICS=0000:41:05.5

**Comment by SchSeba** [comment]
@ognjen011 I also saw you didn't configure hugepages are you sure testpmd doesn't need it for InfiniBand devices?
 another point is you need this capabilities to run the dpdk application and the run as user

```
        capabilities:
          add:
            - IPC_LOCK
            - SYS_RESOURCE
            - NET_RAW
            - NET_ADMIN
        runAsUser: 0
```

**Comment by ognjen011** [comment]
Ok thanks will have a look i did setup hugepages not sure why the pod insists they are not there will check that as well. I can see that in the allocations each node has 1G and 2Mib hugepages as well.  I added capabilities and runAsUser and will do some more tests.

**Comment by SchSeba** [comment]
BTW I know you are not running Openshift but there is a nice documentation about how to run testpmd inside a cluster. you may need to do some stuff manually like CPU isolation but it's not mandatory

https://docs.openshift.com/container-platform/4.11/networking/hardware_networks/using-dpdk-and-rdma.html#nw-example-dpdk-line-rate_using-dpdk-and-rdma

**Comment by ognjen011** [comment]
Ok i am still struggling with this.  I just want to clear something up when i start a dpdk pod should be able to run  ibv_deviceinfo from the pod? 

When i run it i see no devices found 

When i execute dpdk  test i am seeing 

net_mlx5: mlx5.c:3198: mlx5_pci_probe(): no Verbs device matches PCI device 0000:41:07.7, are kernel drivers loaded?
EAL: Requested device 0000:41:07.7 cannot be used

i can see all of the relevant info from the pod when i do ls /dev/invfinibend 

 uverbs0

I can run dpdk-devbnd.py -s from the pod but i cannot run any of the ibv_ commands from the pod.  They all come back empty. 

if i look into that mlx5.c file at that line i can see this function being called

ibv_match[nd] = NULL;
        if (!nd) {
                /* No device matches, just complain and bail out. */
                DRV_LOG(WARNING,
                        "no Verbs device matches PCI device " PCI_PRI_FMT ","
                        " are kernel drivers loaded?",
                        pci_dev->addr.domain, pci_dev->addr.bus,
                        pci_dev->addr.devid, pci_dev->addr.function);
                rte_errno = ENOENT;
                ret = -rte_errno;
                goto exit;
        }

Anyone have any ideas of what might be wrong here. DPDK seems to work on Intel cards but i cannot get it going with Mellanox.
