### ISSUE TITLE
SRIOV/DPDK poor network performance

### ISSUE THREAD

**Issue by ognjen011** [k8snetworkplumbingwg/sriov-network-operator#366]
I am running sriov network operator and when testing network throughput using sriov I am seeing a 1.2mpps limit consistently across different network cards. Is there some built in limit that I am not aware of? DPDK I am seeing bigger numbers but huge packet loss.

**Comment by zeeke** [comment]
Hi @ognjen011 , can you provide more context on your environment?
- SriovNetworkNodePolicies used
- Cluster topology
- NICs vendor/device involved
- Applications used for testing

thanks

**Comment by ognjen011** [comment]
I think it is related to the pktgen linux module it seems it is using a single core to generate traffic and as far as I can tell it has a 10g line rate limit.

**Comment by adrianchiris** [comment]
> The main thing I wanted to check if there is a rate limiter built in and turned on by default when using this network plugin.

There isnt to the best of my knowledge.
