### ISSUE TITLE
SR-IOV Device Plugin daemonset is not deleted

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/sriov-network-operator#385]
Steps to reproduce:
* deploy SR-IOV Network Operator using helm chart
* Apply SriovNetgworkNodePolicy
* uninstall SR-IOV Network Operator 

Expected results:
All resources are cleaned 

Actual results:
SR-IOV Device Plugin is still running

RCA:
The owner of SR-IOV Device Plugin daemonset is `default` policy witch is created by operator and isn't deleted during uninstallation procedure

Proposed solution:
Install `default` policy using helm chart in vanilla k8s and as a part of bundle for OpenShift

**Comment by SchSeba** [comment]
the PR is merged closing
