### ISSUE TITLE
Stop using the beta.kubernetes.io/arch

### ISSUE THREAD

**Issue by pacoxu** [k8snetworkplumbingwg/sriov-network-operator#387]
https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/c173e87cb0eb5449a3e8eec65e9409f112f80697/controllers/sriovnetworknodepolicy_controller.go#L116

https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/c173e87cb0eb5449a3e8eec65e9409f112f80697/bindata/manifests/plugins/sriov-device-plugin.yaml#L29

See https://github.com/kubernetes/kubernetes/issues/89477, https://github.com/kubernetes/kubernetes/issues/89477#issuecomment-603911496.

**Comment by SchSeba** [comment]
this sounds reasonable.

@pacoxu will you be able to open a PR?
