### ISSUE TITLE
sriov-config-daemon and sriov-device-plugins manifests have hardcoded nodeSelectors

### ISSUE THREAD

**Issue by tariq1890** [k8snetworkplumbingwg/sriov-network-operator#417]
We are trying to use `sriov-network-operator`  (by way of Mellanox operator) and we were unable to start up the `sriov-cni` and `sriov-device-plugin` components. This is due to the nodeSelector selecting on node roles that are not made available in our managed clusters. (The notion of masters and workers don't necessarily exist in these clusters, so we use different node role labeling conventions)

The manifests can be seen below:

i) https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/bindata/manifests/plugins/sriov-device-plugin.yaml#L30

ii) https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/eb3d22a45685db2d3318eaabfdfb756b9aa31826/bindata/manifests/daemon/daemonset.yaml#L29

Can we make these configurable?

**Comment by adrianchiris** [comment]
hmm, perhaps we should have `ConfigDaemonNodeSelector`[1] field apply to both config daemon and device plugin.

it makes sense that sriov device plugin deployed by operator will run on same nodes as the sriov config daemon.

defaulting to the current set of node selector labels:
```
      nodeSelector:
        beta.kubernetes.io/os: linux
        node-role.kubernetes.io/worker:
```

Thoughts ?


[1] https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/eb3d22a45685db2d3318eaabfdfb756b9aa31826/api/v1/sriovoperatorconfig_types.go#L29

**Comment by tariq1890** [comment]
That makes sense. So does this mean would have maintain an OperatorConfig CR to set defaults?

**Comment by rollandf** [comment]
> hmm, perhaps we should have `ConfigDaemonNodeSelector`[1] field apply to both config daemon and device plugin.
> 
> it makes sense that sriov device plugin deployed by operator will run on same nodes as the sriov config daemon.
> 
> defaulting to the current set of node selector labels:
> 
> ```
>       nodeSelector:
>         beta.kubernetes.io/os: linux
>         node-role.kubernetes.io/worker:
> ```
> 
> Thoughts ?
> 
> [1]
> 
> https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/eb3d22a45685db2d3318eaabfdfb756b9aa31826/api/v1/sriovoperatorconfig_types.go#L29

Seems it is already implemented as you described:

https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/eb3d22a45685db2d3318eaabfdfb756b9aa31826/controllers/sriovoperatorconfig_controller.go#L141-L155

**Comment by adrianchiris** [comment]
Ah Nice, i missed that.

so it should be just a matter of specifying `ConfigDaemonNodeSelector` in sriovoperatorconfig CR

**Comment by tariq1890** [comment]
Great! I'll test this and get back. This probably needs to be documented. I wasn't really aware of the `SriovOperatorConfigs` CR

**Comment by tariq1890** [comment]
I see that in the sriov-network-operator main logic,  we create a default SRIOV Operator config CR during rutime. What are your thoughts on configuring that via envars? Then we can pass the NodeSelectors and other params as deployment params instead of creating a CR

**Comment by zeeke** [comment]
We already do that for `ENABLE_ADMISSION_CONTROLLER` for `enableAdmissionController` field, so I don't see any particular reason not to proceed that way.

BTW, wouldn't it be cleaner to add a configurable default SriovConfigOperator in the [helm folder](https://github.com/k8snetworkplumbingwg/sriov-network-operator/tree/master/deployment/sriov-network-operator)?

Also, note that default config is created in two locations, not sure which is the winning one:
- [main.go#L247](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/main.go#L247)
- [sriovoperatorconfig_controller.go#L94](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/master/controllers/sriovoperatorconfig_controller.go#L94)

**Comment by SchSeba** [comment]
Hi @tariq1890 any update on this case or we can close it?

**Comment by cyclinder** [comment]
> BTW, wouldn't it be cleaner to add a configurable default SriovConfigOperator in the [helm folder](https://github.com/k8snetworkplumbingwg/sriov-network-operator/tree/master/deployment/sriov-network-operator)?

I think it's reasonable, I can file a PR for it :)

**Comment by SchSeba** [comment]
Thanks!
