### ISSUE TITLE
sriov-network-config-daemon POD/DS are not running.

### ISSUE THREAD

**Issue by HalaharviPedda** [k8snetworkplumbingwg/sriov-network-operator#420]
After deploying (make deploy-setup-k8s) sriov-network-operator ,  sriov-network-config-daemon is not running ( No errors/logs and no information ).

$kubectl get -n sriov-network-operator all
pod/sriov-network-operator-5c7cb646dc-vkpqk   1/1     Running             0          15m

NAME                                         TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/network-resources-injector-service   ClusterIP   XX.XX.XX.XX     <none>        443/TCP   15m
service/operator-webhook-service             ClusterIP   XX.XX.XX.XX   <none>        443/TCP   15m

NAME                                         DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR                                                 AGE
daemonset.apps/network-resources-injector    3         3         0       3            0           beta.kubernetes.io/os=linux                                   15m
daemonset.apps/operator-webhook              3         3         0       3            0           beta.kubernetes.io/os=linux                                   15m
**daemonset.apps/sriov-network-config-daemon   0         0         0       0            0           beta.kubernetes.io/os=linux,node-role.kubernetes.io/worker=   15m**

NAME                                     READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/sriov-network-operator   1/1     1            1           15m

NAME                                                DESIRED   CURRENT   READY   AGE
replicaset.apps/sriov-network-operator-5c7cb646dc   1         1         1       15m

Describe DS of sriov-network-config-daemon , shows no error/log.
Desired Number of Nodes Scheduled: 0
Current Number of Nodes Scheduled: 0
Number of Nodes Scheduled with Up-to-date Pods: 0
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 0 Waiting / 0 Succeeded / 0 Failed
Pod Template:

**Comment by HalaharviPedda** [comment]
@zeeke Thanks for the Response. Please find node data and k8s version.
  Kubelet Version:            v1.26.1

[Node_Description.txt](https://github.com/k8snetworkplumbingwg/sriov-network-operator/files/10999791/Node_Description.txt)

**Comment by zeeke** [comment]
The node has been labeled with `node-role.kubernetes.io/worker=worker`, while the daemonset looks for `node-role.kubernetes.io/worker=`. That's why the daemonset has no pods, I guess.

**Comment by HalaharviPedda** [comment]
> The node has been labeled with `node-role.kubernetes.io/worker=worker`, while the daemonset looks for `node-role.kubernetes.io/worker=`. That's why the daemonset has no pods, I guess.

Thanks For the response.
