### ISSUE TITLE
Does sriov-network-operator support arm?

### ISSUE THREAD

**Issue by zhhray** [k8snetworkplumbingwg/sriov-network-operator#430]
sriov-network-operator whether arm is supported for the container image involved.
Can I deploy it in an arm cluster?

**Comment by SchSeba** [comment]
Hi @zhhray I don't see that we are building the images for other archs.

if you have time to work on that it will be great!
something like this

https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/commit/a8dd3511b3afb66f552b13d5ed3777d6a69e8d76

we will need the same also for all the other operands the sriov operator deploy
https://github.com/k8snetworkplumbingwg/sriov-cni
https://github.com/k8snetworkplumbingwg/ib-sriov-cni
https://github.com/k8snetworkplumbingwg/network-resources-injector

**Comment by cyclinder** [comment]
I can be working on this.
