### ISSUE TITLE
[Enhancement] config-daemon: add a periodic validation routine

### ISSUE THREAD

**Issue by zeeke** [k8snetworkplumbingwg/sriov-network-operator#445]
This enhancement proposes to add a routine to the config-daemon that verifies (in a polling fashion) the
underlying hardware configuration is aligned with the SriovNetworkNodePolicies.

External actors (or privileged workloads) may change the VF's driver [1] or any other underline
hardware configuration that may break subsequent pod deployment. The proposed routine should 
apply the SriovNetworkNodePolicies specs to the hardware whenever a divergence is detected.

[1] https://github.com/k8snetworkplumbingwg/sriov-network-operator/issues/443

**Comment by SchSeba** [comment]
this was implemented https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/530
