### ISSUE TITLE
SR-IOV systemd configuration improvements

### ISSUE THREAD

**Issue by e0ne** [k8snetworkplumbingwg/sriov-network-operator#465]
#365 is merged but we have to follow up with following:
- [ ] unit tests
- [ ] make systemd unit file configurable (e.g. `Wants` and `Before` targets should be customizable)
- [ ] operator should delete systemd service on uninstall 
- [ ] other bugfixes if any

**Comment by e0ne** [comment]
@SchSeba feel free to add anything to the list above

**Comment by SchSeba** [comment]
closing this one with the great work done by @ykulazhenkov
