### ISSUE TITLE
Improve the `config-daemon` observability with k8s `v1.Events`

### ISSUE THREAD

**Issue by zeeke** [k8snetworkplumbingwg/sriov-network-operator#510]
When debugging issues in large clusters, it can be difficult to understand what went wrong with the config daemon by reading the logs only, as they can get lost after config-daemon restarts.

The idea here is to leverage kubernetes `v1.Event` objects as described in the [doc](https://kubernetes.io/blog/2018/01/reporting-errors-using-kubernetes-events/) to mark some important events of the operator lifecycle, such as:
a. The request of the operator to drain a node
b. A node reboot requested by the config-daemon
c. Each transition of any SriovNetworkNodeState status (e.g., Succeeded -> InProgress)

**Comment by rollandf** [comment]
I think this would be a good improvement.

I suggest in addition to the mentioned events we could have also config-daemon start/stop events.

@zeeke can you assign this issue to me?

**Comment by zeeke** [comment]
>I suggest in addition to the mentioned events we could have also config-daemon start/stop events.

It sounds good to me. I'll also discuss this issue in the next community meeting
