### ISSUE TITLE
Stop default creation of SriovOperatorConfig and Policy

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-operator#592]
Summarizing what was discussed in recent community meetings:

- [x] Stop the creation of SriovOperatorConfig by default
- [x] Stop the creation of SriovPolicy by default
- [x] Support only one SriovOperatorConfig named "default"
- [x] Move ownerRef of all components the operator creates to the "default" OperatorConfig CR instead of "default" SriovPolicy CR
- [x] Block creation of non "default" SriovOperatorConfig CR in webhook

**Comment by adrianchiris** [comment]
Note on the last bullet : we already do so today

**Comment by zeeke** [comment]
@adrianchiris can we close this? I see no other todo item left

**Comment by adrianchiris** [comment]
Yes we can. 

closing as dependent PRs merged. Thx for the reviews !
