### ISSUE TITLE
Use per node device plugin config hash

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-operator#619]
Today `SriovNetworkNodeState.Spec.dpConfigVersion` contains the (fnv)hash of device plugin config map data.
that means that each time this config us updated, this hash willl change and trigger reconcile of config daemon.

Since this config map contains per-node device plugin configurations, it only makes sense to calculate hash for the specific node data instead of the entire thing thus preventing un-needed operations by sriov config daemon.

a non-existing sriov config map and an "empty" entry in the config map for the node should yield the same hash.
since intially config map will not exist.

```yaml
apiVersion: v1
data:
  worker-node-2: '{"resourceList":null}'
kind: ConfigMap
metadata:
  creationTimestamp: "2024-02-06T11:59:28Z"
  name: device-plugin-config
  namespace: sriov-network-operator
  resourceVersion: "9112888"
  uid: 59155454-a365-4c95-b2d5-bace3e06d01f
```

**Comment by SchSeba** [comment]
question here I never understand why we really need the `dpConfigVersion` can we drop that ?

**Comment by SchSeba** [comment]
This PR https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/669 should remove it

**Comment by SchSeba** [comment]
closing this one we don't have `dpConfigVersion` anymore
