### ISSUE TITLE
sriov-device-plugin config map created by SriovNetworkNodePolicy controller is never cleaned up

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-operator#620]
we set no OwnerRef so there is no cleanup.
also the Reconcile flow does not contain logic to explicitly clean it.

Suggestion: set SriovOperatorConfig "default" obj as its owner like set for sriov-device-plugin

**Comment by adrianchiris** [comment]
@SchSeba @zeeke  WDYT ?

RE:
> Suggestion: set SriovOperatorConfig "default" obj as its owner like set for sriov-device-plugin

**Comment by zeeke** [comment]
That sounds good to me

**Comment by adrianchiris** [comment]
#623

**Comment by SchSeba** [comment]
closed by https://github.com/k8snetworkplumbingwg/sriov-network-operator/pull/623
