### ISSUE TITLE
Looking for github release criteria

### ISSUE THREAD

**Issue by martinkennelly** [k8snetworkplumbingwg/sriov-network-operator#69]
What criteria are we waiting for to produce a release of this operator?

**Comment by adrianchiris** [comment]
Hi Martin ! thanks for bringing this up.

We should IMO define what we would like to land in the first release.

From my side id really like to have the following addressed as part of the first release:

- #39 Support changing Eswitch mode of SR-IOV NICs for kubernetes deployment 
- #75 Support Switchdev for kernel 5.8 and above
- #72 Set link state up for target ports of SriovNetworkNodePolicy for kubernetes cluster
- Potential bug fixes which may be discovered internally

Once we have a list we can open a V1.0.0 issue to track WDYT?

**Comment by Mmduh-483** [comment]
#62 Support CLUSTER_TYPE  env var

**Comment by zshi-redhat** [comment]
Make kubernetes as default platform to deploy sriov-network-operator
Add document for deploying sriov-network-operator on kubernetes (e.g. webhooks cannot be deployed automatically on vanilla k8s platform as of now)

**Comment by martinkennelly** [comment]
I think updating this would be good to add too: 
#71 Updating the hardware compatibility list

**Comment by pliurh** [comment]
I think we are ok to have 1.0.0 release with the above items. I'll create an issue to track it.

**Comment by martinkennelly** [comment]
Issue objective complete
