### ISSUE TITLE
OCI Helm chart references broken sriov-cni

### ISSUE THREAD

**Issue by ianb-mp** [k8snetworkplumbingwg/sriov-network-operator#761]
The OCI Helm chart for v1.3.0 is currently referencing [sriov-cni](https://github.com/k8snetworkplumbingwg/sriov-cni) v2.8.0 which is [broken for recent Linux kernels](https://github.com/k8snetworkplumbingwg/sriov-cni/issues/303).

It would be good to rebuild the OCI Helm chart so that it references sriov-cni v2.8.1 which has [the fix](https://github.com/k8snetworkplumbingwg/sriov-cni/pull/309)

In the meantime, users of the OCI Helm chart can override the sriov-cni image like this:
```
$ helm install -n sriov-network-operator --create-namespace \
  --version 1.3.0 \
  --set sriovOperatorConfig.deploy=true sriov-network-operator \
  --set images.sriovCni=ghcr.io/k8snetworkplumbingwg/sriov-cni:v2.8.1 \
  oci://ghcr.io/k8snetworkplumbingwg/sriov-network-operator-chart
```

**Comment by SchSeba** [comment]
Hi @ianb-mp,
Thanks for the issue we are going to make another release of the sriov-network-operator we are just waiting for one more PR to get in the operator

**Comment by adrianchiris** [comment]
v1.4.0 has been released.
