### ISSUE TITLE
sriov-network-operator v1.3.0 released but still shows 1.2.0 in Helm chart

### ISSUE THREAD

**Issue by jslouisyou** [k8snetworkplumbingwg/sriov-network-operator#762]
Hello, sriov-network-operator team.

It seems that `sriov-network-operator` v1.3.0 was released last month, but still shows v1.2.0 in [here](https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/v1.3.0/deployment/sriov-network-operator-chart/Chart.yaml).
```
apiVersion: v2
name: sriov-network-operator-chart
version: 1.2.0
kubeVersion: '>= 1.16.0-0'
appVersion: 1.2.0
description: SR-IOV network operator configures and manages SR-IOV networks in the kubernetes cluster
type: application
keywords:
  - sriov
home: https://github.com/k8snetworkplumbingwg/sriov-network-operator
sources:
  - https://github.com/k8snetworkplumbingwg/sriov-network-operator
```

I'm not sure if it's fine to use the Helm chart from with v1.3.0 tag.
Could you verify whether it's alright to use this?

Thanks!

**Comment by SchSeba** [comment]
Hi @adrianchiris I think we need to add the version update to the script right?

**Comment by adrianchiris** [comment]
we update image chart in-place before publish. so the chart in the published oci image should contain the correct info.

see: https://github.com/k8snetworkplumbingwg/sriov-network-operator/blob/9dbf2b1b5fd1ff7e836aff169b8aabf020a2840e/hack/release/chart-update.sh#L70

the chart in the proj is for dev purposes.

**Comment by adrianchiris** [comment]
submitted #764

**Comment by SchSeba** [comment]
great thanks!
closing this one
