### ISSUE TITLE
Add Intel Corporation Ethernet Controller E810-XXV for backplane,  E823-L for SFP,  E823-L for backplane for NetSec Accelerator Cards

### ISSUE THREAD

**Issue by wizhaoredhat** [k8snetworkplumbingwg/sriov-network-operator#789]
Intel Corporation Ethernet Controller E810-XXV for backplane
Vendor ID: 0x8086
PF Device ID: 0x1599
VF Device ID: 0x1889

Intel Corporation Ethernet Connection E823-L for SFP
Vendor ID: 0x8086
PF Device ID: 0x124d
VF Device ID: 0x1889

Intel Corporation Ethernet Connection E823-L for backplane
Vendor ID: 0x8086
PF Device ID: 0x124c
VF Device ID: 0x1889

We need to introduce these new ethernet controllers for the NetSec Accelerator Card.

@Eoghan1232 @SchSeba

**Comment by wizhaoredhat** [comment]
cc: @bn222

**Comment by adrianchiris** [comment]
@wizhaoredhat  anything else missing or this one can be closed ?

**Comment by wizhaoredhat** [comment]
Yes this can be closed! Thanks!
