### ISSUE TITLE
Add github Actions to create and push project images to container registry

### ISSUE THREAD

**Issue by adrianchiris** [k8snetworkplumbingwg/sriov-network-operator#82]
- Generate GH token and store it as a secret to be used by the workflows
- Create github actions for:
  - Build and push images on PR merge.
  - Build and push images on tag creation.

**Artifacts to be created:**
  - sriov-network-operator
  - sriov-network-operator-config-daemon
  - sriov-network-operator-webhook

**Comment by adrianchiris** [comment]
@pliurh i think the PAT you generated does not have enough permissions (write permissions) in order to push images.
i will close this issue once we got our first set of images available.

**Comment by pliurh** [comment]
Yes. I'll ask Doug to see how we can solve it. It looks like we need the PAT from the owner of the org.

**Comment by pliurh** [comment]
With #88, the images can be built as expected.

**Comment by adrianchiris** [comment]
according to github docs a PAT is needed for ghcr.

https://docs.github.com/en/packages/guides/migrating-to-github-container-registry-for-docker-images#authenticating-with-the-container-registry

anyway, i see we got our first images !

this can now be closed
